"""add marketplace community and assets

Revision ID: 2165c0ae0f8b
Revises: c7f3a2d9e8b1
Create Date: 2026-06-22 14:14:35.667237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2165c0ae0f8b'
down_revision: Union[str, None] = 'c7f3a2d9e8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_service_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('expert_type', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expert_service_packages'))
    )
    op.create_index(op.f('ix_expert_service_packages_expert_type'), 'expert_service_packages', ['expert_type'], unique=False)
    op.create_index(op.f('ix_expert_service_packages_status'), 'expert_service_packages', ['status'], unique=False)
    op.create_table('community_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], name=op.f('fk_community_reports_reporter_id_user')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_community_reports_reviewed_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_reports'))
    )
    op.create_index(op.f('ix_community_reports_reporter_id'), 'community_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_community_reports_status'), 'community_reports', ['status'], unique=False)
    op.create_index(op.f('ix_community_reports_target_id'), 'community_reports', ['target_id'], unique=False)
    op.create_table('expert_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('expert_type', sa.String(length=30), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_expert_profiles_reviewed_by_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_expert_profiles_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expert_profiles'))
    )
    op.create_index(op.f('ix_expert_profiles_expert_type'), 'expert_profiles', ['expert_type'], unique=False)
    op.create_index(op.f('ix_expert_profiles_status'), 'expert_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_expert_profiles_user_id'), 'expert_profiles', ['user_id'], unique=True)
    op.create_table('naming_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('moral', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('domain_status', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_naming_assets_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_naming_assets')),
    sa.UniqueConstraint('user_id', 'thread_id', 'name', name='uq_naming_asset_owner_thread_name')
    )
    op.create_index(op.f('ix_naming_assets_thread_id'), 'naming_assets', ['thread_id'], unique=False)
    op.create_index(op.f('ix_naming_assets_user_id'), 'naming_assets', ['user_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('cover_visual_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('vote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_community_posts_author_id_user')),
    sa.ForeignKeyConstraint(['cover_visual_id'], ['brand_visuals.id'], name=op.f('fk_community_posts_cover_visual_id_brand_visuals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_posts'))
    )
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_posts_category'), 'community_posts', ['category'], unique=False)
    op.create_index(op.f('ix_community_posts_created_time'), 'community_posts', ['created_time'], unique=False)
    op.create_index(op.f('ix_community_posts_status'), 'community_posts', ['status'], unique=False)
    op.create_table('expert_service_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finance_order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('naming_asset_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='PENDING_PAYMENT', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], name=op.f('fk_expert_service_orders_customer_id_user')),
    sa.ForeignKeyConstraint(['expert_id'], ['expert_profiles.id'], name=op.f('fk_expert_service_orders_expert_id_expert_profiles')),
    sa.ForeignKeyConstraint(['finance_order_id'], ['orders.id'], name=op.f('fk_expert_service_orders_finance_order_id_orders')),
    sa.ForeignKeyConstraint(['naming_asset_id'], ['naming_assets.id'], name=op.f('fk_expert_service_orders_naming_asset_id_naming_assets')),
    sa.ForeignKeyConstraint(['package_id'], ['expert_service_packages.id'], name=op.f('fk_expert_service_orders_package_id_expert_service_packages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expert_service_orders')),
    sa.UniqueConstraint('finance_order_id', name=op.f('uq_expert_service_orders_finance_order_id'))
    )
    op.create_index(op.f('ix_expert_service_orders_customer_id'), 'expert_service_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_expert_service_orders_expert_id'), 'expert_service_orders', ['expert_id'], unique=False)
    op.create_index(op.f('ix_expert_service_orders_status'), 'expert_service_orders', ['status'], unique=False)
    op.create_table('community_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('moral', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('vote_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('fk_community_candidates_post_id_community_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['naming_assets.id'], name=op.f('fk_community_candidates_source_asset_id_naming_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_candidates'))
    )
    op.create_index(op.f('ix_community_candidates_post_id'), 'community_candidates', ['post_id'], unique=False)
    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('fk_community_comments_post_id_community_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_community_comments_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_comments'))
    )
    op.create_index(op.f('ix_community_comments_created_time'), 'community_comments', ['created_time'], unique=False)
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_comments_user_id'), 'community_comments', ['user_id'], unique=False)
    op.create_table('expert_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('professional_analysis', sa.Text(), nullable=False),
    sa.Column('phonetic_semantic_analysis', sa.Text(), nullable=False),
    sa.Column('communication_advantages', sa.Text(), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_order_id'], ['expert_service_orders.id'], name=op.f('fk_expert_reports_service_order_id_expert_service_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expert_reports')),
    sa.UniqueConstraint('service_order_id', name=op.f('uq_expert_reports_service_order_id'))
    )
    op.create_table('expert_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], name=op.f('fk_expert_reviews_customer_id_user')),
    sa.ForeignKeyConstraint(['expert_id'], ['expert_profiles.id'], name=op.f('fk_expert_reviews_expert_id_expert_profiles')),
    sa.ForeignKeyConstraint(['service_order_id'], ['expert_service_orders.id'], name=op.f('fk_expert_reviews_service_order_id_expert_service_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expert_reviews')),
    sa.UniqueConstraint('service_order_id', name='uq_expert_review_service_order')
    )
    op.create_index(op.f('ix_expert_reviews_expert_id'), 'expert_reviews', ['expert_id'], unique=False)
    op.create_table('community_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['community_candidates.id'], name=op.f('fk_community_votes_candidate_id_community_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('fk_community_votes_post_id_community_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_community_votes_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_votes')),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_community_vote_post_user')
    )
    op.create_index(op.f('ix_community_votes_post_id'), 'community_votes', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_votes_user_id'), 'community_votes', ['user_id'], unique=False)
    op.add_column('brand_visuals', sa.Column('image_path', sa.String(length=1000), nullable=True))
    op.add_column('brand_visuals', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    visual_columns = {column['name'] for column in sa.inspect(op.get_bind()).get_columns('brand_visuals')}
    if 'error_message' in visual_columns:
        op.drop_column('brand_visuals', 'error_message')
    if 'image_path' in visual_columns:
        op.drop_column('brand_visuals', 'image_path')
    op.drop_table('community_votes')
    op.drop_table('expert_reviews')
    op.drop_table('expert_reports')
    op.drop_table('community_comments')
    op.drop_table('community_candidates')
    op.drop_table('expert_service_orders')
    op.drop_table('community_posts')
    op.drop_table('naming_assets')
    op.drop_table('expert_profiles')
    op.drop_table('community_reports')
    op.drop_table('expert_service_packages')
