"""add vip membership and quotas

Revision ID: 0bb0a0fc0772
Revises: 2165c0ae0f8b
Create Date: 2026-06-22 20:52:44.391362

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb0a0fc0772'
down_revision: Union[str, None] = '2165c0ae0f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quota_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('naming_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('visual_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_daily_quota_usage_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_quota_usage')),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_daily_quota_user_date')
    )
    op.create_index(op.f('ix_daily_quota_usage_usage_date'), 'daily_quota_usage', ['usage_date'], unique=False)
    op.create_index(op.f('ix_daily_quota_usage_user_id'), 'daily_quota_usage', ['user_id'], unique=False)
    op.create_table('user_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package_config.id'], name=op.f('fk_user_memberships_package_id_package_config')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_memberships_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_memberships'))
    )
    op.create_index(op.f('ix_user_memberships_end_time'), 'user_memberships', ['end_time'], unique=False)
    op.create_index(op.f('ix_user_memberships_user_id'), 'user_memberships', ['user_id'], unique=True)
    op.add_column('expert_service_orders', sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute('UPDATE expert_service_orders SET original_amount = amount')
    op.alter_column('expert_service_orders', 'original_amount', existing_type=sa.Numeric(10, 2), nullable=False)
    op.add_column('expert_service_orders', sa.Column('discount_rate', sa.Numeric(precision=4, scale=2), server_default='1.00', nullable=False))
    op.add_column('package_config', sa.Column('package_code', sa.String(length=50), nullable=True))
    op.add_column('package_config', sa.Column('duration_days', sa.Integer(), server_default='0', nullable=False))
    op.add_column('package_config', sa.Column('naming_daily_quota', sa.Integer(), server_default='0', nullable=False))
    op.add_column('package_config', sa.Column('visual_daily_quota', sa.Integer(), server_default='0', nullable=False))
    op.add_column('package_config', sa.Column('expert_discount', sa.Numeric(precision=4, scale=2), server_default='1.00', nullable=False))
    op.create_unique_constraint(op.f('uq_package_config_package_code'), 'package_config', ['package_code'])
    package_table = sa.table(
        'package_config',
        sa.column('name', sa.String()), sa.column('package_code', sa.String()),
        sa.column('price', sa.Numeric()), sa.column('api_quota', sa.Integer()),
        sa.column('duration_days', sa.Integer()), sa.column('naming_daily_quota', sa.Integer()),
        sa.column('visual_daily_quota', sa.Integer()), sa.column('expert_discount', sa.Numeric()),
        sa.column('description', sa.Text()), sa.column('status', sa.String()),
        sa.column('created_time', sa.DateTime()), sa.column('updated_time', sa.DateTime()),
    )
    now = datetime.now()
    op.bulk_insert(package_table, [
        {'name': '月度 VIP', 'package_code': 'VIP_MONTHLY', 'price': 19.90, 'api_quota': 0,
         'duration_days': 30, 'naming_daily_quota': 100, 'visual_daily_quota': 20,
         'expert_discount': 0.90, 'description': '每日100次智能起名、20次视觉生成，专家服务9折',
         'status': 'ACTIVE', 'created_time': now, 'updated_time': now},
        {'name': '年度 VIP', 'package_code': 'VIP_YEARLY', 'price': 199.00, 'api_quota': 0,
         'duration_days': 365, 'naming_daily_quota': 100, 'visual_daily_quota': 20,
         'expert_discount': 0.90, 'description': '全年高额度服务与专家服务9折',
         'status': 'ACTIVE', 'created_time': now, 'updated_time': now},
    ])
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('created_time', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('user_memberships')
    op.drop_table('daily_quota_usage')
    op.execute("UPDATE orders SET package_id = NULL WHERE package_id IN (SELECT id FROM package_config WHERE package_code IN ('VIP_MONTHLY', 'VIP_YEARLY'))")
    op.execute("DELETE FROM package_config WHERE package_code IN ('VIP_MONTHLY', 'VIP_YEARLY')")
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'created_time')
    op.drop_column('user', 'bio')
    op.drop_constraint(op.f('uq_package_config_package_code'), 'package_config', type_='unique')
    op.drop_column('package_config', 'expert_discount')
    op.drop_column('package_config', 'visual_daily_quota')
    op.drop_column('package_config', 'naming_daily_quota')
    op.drop_column('package_config', 'duration_days')
    op.drop_column('package_config', 'package_code')
    op.drop_column('expert_service_orders', 'discount_rate')
    op.drop_column('expert_service_orders', 'original_amount')
